name: darwin

on:
  pull_request:
    branches:
      - master
    paths:
      - '**'
      - '!**.md'
  push:
    branches:
      - master
    paths:
      - '**'
      - '!**.md'
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC

jobs:
  darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/hardselius/nix-flakes-installer/releases/download/nix-2.4pre20210326_dd77f71/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v9
        with:
          name: hardselius
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - if: ${{ github.event_name == 'schedule' && success() }}
        run: |
          nix flake update --recreate-lock-file
      - run: |
          echo -e "run\tprivate/var/run" | sudo tee -a /etc/synthetic.conf >/dev/null
          /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -B 2>/dev/null || true
      - run: |
          nix-env --set-flag priority 0 cachix
      - run: |
          nix build .#darwinConfigurations.bootstrap.system
      - run: |
          ./result/sw/bin/darwin-rebuild switch --flake .#bootstrap
      - run: |
          . /etc/static/bashrc
          sudo mv /etc/nix/nix.conf /etc/nix/nix.conf.backup-before-darwin
          sudo mv /etc/zshenv /etc/zshenv.backup-before-darwin
          darwin-rebuild switch --flake .#ghActions
      - if: ${{ github.event_name == 'schedule' && success() }}
        run: |
          git add --all
          git commit -m "Update sources"
          git push
