name: Build NixOS WSL environment

on:
  push:
    branches:
      - '**'

jobs:
  build-wsl:
    runs-on: windows-latest
    steps:
      # - name: Install Ubuntu
      #   run: wsl --install --distribution Ubuntu

      - name: Install NixOS WSL
        run: |
          $url = "https://github.com/nix-community/NixOS-WSL/releases/download/21.11-d89f18a1/nixos-wsl-installer-fixed.tar.gz"
          $dest = "c:\temp\nixos-wsl-installer.tar.gz"
          Invoke-WebRequest -Uri $url -OutFile $dest
          wsl --import NixOS .\NixOS\ $dest --version 2

      - name: Run NixOS
        run: wsl --distribution NixOS
