name: Build NixOS WSL environment

on:
  push:
    branches:
      - '**'

jobs:
  build-wsl:
    runs-on: windows-latest
    steps:
      - name: Download NixOS distro
        run: curl.exe -L https://github.com/nix-community/NixOS-WSL/releases/download/21.11-d89f18a1/nixos-wsl-installer-fixed.tar.gz -o nixos-wsl-installer.tar.gz

      - name: Check the directory
        run: dir

      - name: Import NixOS
        run: wsl --import NixOS .\NixOS\ nixos-wsl-installer.tar.gz --version 2

      - name: Check the directory again
        run: dir

      - name: Run NixOS
        run: wsl --distribution NixOS

      # - name: Run NixOS
      #   run: wsl --distribution NixOS
