name: Build NixOS WSL environment

on:
  push:
    branches:
      - '**'

jobs:
  build-wsl:
    runs-on: windows-latest
    steps:
      - name: Install NixOS WSL
        shell: cmd
        run: |
          curl.exe -L https://github.com/nix-community/NixOS-WSL/releases/download/21.11-d89f18a1/nixos-wsl-installer-fixed.tar.gz -o nixos-wsl-installer.tar.gz
          wsl --import NixOS .\NixOS\ .\nixos-wsl-install.tar.gz --version 2
          wsl --distribution NixOS

      # - name: Run NixOS
      #   run: wsl --distribution NixOS
